/**
 * A place holder for constants used in different apex components across the system.
 * 
 * @author      Cloud Sherpas
 * @createddate 29-Oct-2015
 */   
public class CHConstants {
    public static final String VALIDATE_ACTION = 'validate';
    public static final String NEW_LOCATION_ACTION = 'newlocation';
    public static final String ACCOUNT_RECORD_TYPE_HR_TALENT_POOLS = 'HR_Talent_Pools';
    public static final String ACCOUNT_RECORD_TYPE_CUSTOMER = 'Customer';
    public static final String ACCOUNT_RECORD_TYPE_COMPETITOR = 'UMO Competitor';
    public static final String ACCOUNT_RECORD_TYPE_RFOO = 'RFOO';
	public static final String ACCOUNT_RECORD_TYPE_COMPETITOR_DeveloperName = 'Competitor';
    public static final String ACCOUNT_RECORD_TYPE_CUSTOMER_Chain = 'Customer_Chain';
	public static final String ACCOUNT_RECORD_TYPE_CUSTOMERChain = 'Customer Chain';
    public static final String ACCOUNT_RECORD_TYPE_CHAIN = 'Chain';
    public static final String ACCOUNT_RECORD_TYPE_CUSTOMER_LOCATION = 'Customer Location';
    Public static final String ACCOUNT_RECORD_TYPE_KEY_ACCOUNT = 'Key Account';
    public static final String ACCOUNT_RECORD_TYPE_BROKER = 'Broker';
    public static final String ACCOUNT_RECORD_TYPE_BROKER_LOCATION = 'Broker Location';
    public static final String ACCOUNT_RECORD_TYPE_DISTRIBUTOR = 'Distributor';
    public static final String ACCOUNT_RECORD_TYPE_DISTRIBUTOR_LOCATION = 'Distributor Location';
    public static final String ACCOUNT_RECORD_TYPE_PROSPECT_GEN = 'Prospect Gen';
      public static final String ACCOUNT_RECORD_TYPE_CUSTOMER_Chain_DEVELOPER_NAME = 'Customer_Chain';
    public static final String ACCOUNT_RECORD_TYPE_PROSPECT_DEVELOPER_NAME = 'Prospect';
    public static final String ACCOUNT_RECORD_TYPE_PROSPECT_GEN_DEVELOPER_NAME = 'Prospect_Gen';
    public static final String ACCOUNT_RECORD_TYPE_CUSTOMER_LOCATION_DEVELOPER_NAME = 'Customer_Location';
    public static final String ACCOUNT_RECORD_TYPE_BROKER_LOCATION_DEVELOPER_NAME = 'Broker_Location';
    public static final String ACCOUNT_RECORD_TYPE_DISTRIBUTOR_LOCATION_DEVELOPER_NAME = 'Distributor_Location';
    public static final String ACCOUNT_RECORD_TYPE_REGIONAL_ACCOUNT_DEVELOPER_NAME='Key_Account';
    public static final String ACCOUNT_TYPE_SHIPTO_GEN = 'ShipTo/Gen';
    public static final String ACCOUNT_TYPE_CUSTOMER = 'Customer';
    public static final String ACCOUNT_TYPE_BROK_GEN = 'Brok/Gen';
    public static final String ACCOUNT_TYPE_DIST_GEN = 'Dist/Gen';
    public static final String ACCOUNT_TYPE_PRICING_CHAIN = 'Pricing Chain';
    public static final String ACCOUNT_TYPE_PARENT_REPORTING_CHAIN = 'Parent Reporting Chain';
    public static final String ACCOUNT_TYPE_REPORTING_CHAIN = 'Reporting Chain';
    public static final String ACCOUNT_TYPE_TRAN = 'TRAN';
    public static final String ACCOUNT_TYPE_RAIL = 'RAIL';
    public static final String ACCOUNT_TYPE_RIG = 'Rig';
    public static final String ACCOUNT_TYPE_CORPORATE = 'Corporate';
    public static final String ACCOUNT_TYPE_PROSP_GEN = 'Prospect Gen';
    public static final String DEPARTMENT_CODE_MAIN = 'MAIN';
    public static final String DEPARTMENT_CODE_MANI = 'MANI';
    public static final String DEPARTMENT_CODE_ACCT = 'ACCT';
    public static final String DEPARTMENT_CODE_CERT = 'CERT';
    public static final String DEPARTMENT_CODE_AP = 'AP';
    public static final String DEPARTMENT_CODE_PO = 'PO';
    public static final String Ownerupdate = 'Ownerupdate';
    public static final String ACCOUNT_WIN_VALIDATE_CREATE = 'WinValidateAndCreate';
    public static final String OCRBatchUpdate = 'OCROwnerUpdateBatchProcess';
    public static final String BrokerRecordTypeUpdate = 'BrokerRecordTypeUpdate';
	public static final String KeyAccountUpdate = 'Key Account Update';
	public static final String ContactErrorUpdate = 'Contact Error Update';
    public static final String CONTACT_DEPARTMENT_MAIN_CONTACT = 'Main Contact';
    public static final String ACCOUNT_CREDIT_STATUS_HOLD = 'Hold';
    public static final String ACCOUNT_CREDIT_TERMS_CASH_ON_DELIVERY = 'Cash on Delivery';
    public static final String ACCOUNT_CREDIT_TERMS_NET_15_DAYS = 'Net 15 days';
    public static final String ACCOUNT_CREDIT_TERMS_NET_30_DAYS = 'Net 30 Days';
    public static final String ACCOUNT_CREDIT_TERMS_NA = 'N/A';
    public static final String ACCOUNT_CLASS_INDIVIDUAL_HOMEOWNERS = 'Individuals & Homeowners';
    public static final String ACCOUNT_RANK_CH_A_LARGE_ABOVE_200K = 'CH A Large >200K';
    public static final String ACCOUNT_COUNTRY_CA = 'CA';
    public static final String ACCOUNT_COUNTRY_US = 'US';
    public static final String ACCOUNT_EPA_ID_NONREQUIRED = 'NONREQUIRED';
    public static final String ACCOUNT_EPA_ID_FCCANADA = 'FCCANADA';
    public static final String INTEGRATION_PROFILE_NAME = 'Integration';
    public static final String APIINTEGRATION_PROFILE_NAME = 'Salesforce API Only System Integrations';
    public static final String ACCOUNT_GEN_STATUS_LARGE_QTY_GENERATOR = 'Large Quantity Generator';
    public static final String ACCOUNT_GEN_STATUS_SMALL_QTY_GENERATOR = 'Small Quantity Generator';
    public static final String ACCOUNT_GEN_STATUS_CONDITIONALLY_QTY_GENERATOR = 'Conditionally Exempt Sm Qty Generator';
    public static final String ACCOUNT_GEN_STATUS_NULL = 'Null';
	public static final String ACCOUNT_GEN_STATUS_UNDETERMINED = 'Undetermined';  
    public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_CLEAN_HARBORS = 'Clean Harbors';
    public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_CYN = 'CYN';
    public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_SAFETY_KLEEN = 'Safety Kleen';
    public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_SYNERGY = 'Synergy';
    public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_THERMO_FLUIDS = 'Thermo Fluids';
    public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_EMERALD = 'Emerald Services';
	public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_HPC_INDUSTRIAL = 'HPC Industrial';
    public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_RS = 'RS Used Oil';
	public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_DFW = 'DFW';
    public static final String ACCOUNT_GEN_STATUS_ABV_LARGE_QTY_GENERATOR = 'L';
    public static final String ACCOUNT_GEN_STATUS_ABV_SMALL_QTY_GENERATOR = 'S';
    public static final String ACCOUNT_GEN_STATUS_ABV_CONDITIONALLY_QTY_GENERATOR = 'V';
    public static final String ACCOUNT_GEN_STATUS_ABV_NULL = 'null';
    public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_ABV_CLEAN_HARBORS = 'CH';
    public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_ABV_SYNERGY = 'SY';
    public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_ABV_CYN = 'CYN';
    public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_ABV_SAFETY_KLEEN = 'SK';
    public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_ABV_THERMO_FLUIDS = 'TF';
    public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_ABV_EMERALD = 'EM';
    public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_ABV_RS = 'RS';
	public static final String ACCOUNT_PRIMARY_SERVICE_PROVIDER_ABV_DFW = 'DFW';
    public static final String EPA_JSON_REQ_EPA_ID = 'EpaId';
    public static final String EPA_JSON_REQ_ADDRESS_LINE_1 = 'AddressLine1';
    public static final String EPA_JSON_REQ_CITY = 'City';
    public static final String EPA_JSON_REQ_STATE = 'State';
    public static final String EPA_JSON_RES_STATE_EPA_ID = 'StateEpaId';
    public static final String EPA_JSON_RES_GENREG_ID = 'GenregId';
    public static final String EPA_JSON_REQ_COUNTRY_CODE = 'CountryCode';
    public static final String EPA_JSON_REQ_GENERATOR_STATUS = 'GeneratorStatus';
    public static final String EPA_JSON_REQ_PRIMARY_SERVICE_PROVIDER = 'PrimaryServiceProvider';
    public static final String EPA_JSON_RES_VALID_EPA = 'ValidEpa';
    public static final String EPA_JSON_RES_MESSAGE = 'Message';
    public static final String ACCOUNT_RECORD_TYPE_CORPORATE = 'Corporate';
    public static final String ACCOUNT_RECORD_TYPE_CORPRETIRED = 'Corporate - Retired';
    public static final String ACCOUNT_PROSPECT_STATUS='Prospect';
    public static final String ACCOUNT_DRAFT_STATUS='Draft';
    public static final String CONTACT_OBJNAME='CONTACT';
    public static final String NOT_ELIGIBLE_INTEGRATION_USER ='Integration User';
    public static final string INACTIVATION_REQUEST = 'Inactivation Request';
	public static final String ACCOUNT_BILLING_ADDRESS_CHANGED ='Billing Address';
    public static final String ACCOUNT_SHIPPING_ADDRESS_CHANGED ='Shipping Address';
	public static final String CPG_SUBMISSION_vALIDATION_ERROR_MESSAGE = 'The CPG Case is not allowed to be submitted for Approval.';
    
    //Case Status
    public static final String CASE_STATUS_NEW = 'New'; 
    public static final String CASE_MESSAGE='One of the fields that you tried to edit is currently in an account change review and cannot be edited until the case is closed. Please review open cases on the account for more detail';
    
    //Case Types
    public static final string CASE_TYPE_SERVICE = 'E-Billing Service';
    
    //Case WIN Sync Status
    public static final string CASE_WIN_SYNC_STATUS_SUCCESSFUL = 'Successful';
    public static final string CASE_WIN_SYNC_STATUS_FAILED = 'Failed';
    
    //Case Record Type Names
    public static final string CASE_RECORD_TYPE_NAME_NSB_WIN = 'Non Standard Billing WIN';
    public static string CASE_RECORD_TYPE_NAME_COWB = 'Non Standard Billing Closed Order';
    public static string CASE_RECORD_TYPE_NAME_INV_DEL = 'Invoice Delivery';
    public static string CASE_RECORD_TYPE_ACCOUNT_UPDATE_VALIDATIONS = 'Account_Update_Validations';
    
    //Account Record Type Names
    public static final string ACCOUNT_RECORD_TYPE_NAME_BRANCH = 'Branch';
    
    //Integration Parameters
    public static final String INTEGRATION_SOURCE_APP_NSB = 'NSB';
    public static final String INTEGRATION_SOURCE_APP_COWB = 'COWB';
    public static final String INTEGRATION_SOURCE_APP_INV_DEL = 'Invoice Delivery';
    public static final String INVOICE_DELIVERY_CASE_DESCRIPTION = 'Currently there is no Primary email address listed in Invoice Delivery Requirements. Please confirm the primary email address with the customer and click on the Invoice Delivery Requirements button to update the email address';
    public static final String NSB_CASE_TYPE_PO = 'E-Billing Customer PO';
    public static final String PO_TIMING = 'At Time of Service';	
 
    //Queue Names
    public static final String QUEUE_NAME_PO_CASE_QUEUE = 'PO Case Queue';
    public static final String QUEUE_NAME_BRANCH_DEFAULT_QUEUE = 'Branch Default Queue';
	
	//Case constants
	public static final String Submit_For_Reject_Error = 'Your approval request cannot be submitted until you add at least one case comment. Close this window, add a case comment to the case, then submit for approval.'; 
    
}